/*******************************************************************************
 *  Dice Roller 2 is a tabletop rpg dice roll utility tool
 *     Copyright (C) 2014, 2015 David Meersteiner
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *     
 *     Contact me under:
 *     
 *     dmeersteiner@gmail.com
 *     
 *     David Meersteiner
 *     Am Hang 10
 *     94253 Bischofsmais
 *     GERMANY
 *******************************************************************************/
package de.dm.dr2.data.consolemessages;

/**
 * 
 * The implementations of the {@code ConsoleMessage}
 * abstract class are used by {@code Console} to format
 * a data class into an {@code String} that will be read 
 * by the user.
 * 
 * @author D. Meersteiner
 * @see de.dm.dr2.main.Main
 */
public abstract class ConsoleMessage {
	
	/**
	 * The Strings generated by this method must be readable for the user.
	 * <p>
	 * The Message is the everything, including the Command, the rolled
	 * values and the final value.  
	 * @return the message formatted in a {@code String}
	 */
	public abstract String getMessage();
	
	/**
	 * The Strings generated by this method must be readable for the user.
	 * <p>
	 * The value is just the final value, without the Command or the
	 * rolled values
	 * @return the message formatted in a {@code String}
	 */
	public abstract String getValue();
}
